In [11]:
import numpy as np

In [12]:
mylist = [1 ,2, 3]
n = np.array(mylist)
n

array([1, 2, 3])

In [13]:
type(mylist)

list

In [14]:
type(n)

numpy.ndarray

In [15]:
list_of_lists = np.array([[1,2,3], [4,5,6], [7,8,9]])
list_of_lists

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
list_of_lists.shape #dimensions of array

(3, 3)

In [18]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [24]:
for i in range(0,10,2):
    print(i)

0
2
4
6
8


In [27]:
zero = np.zeros(10) #array full of zeros
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.ones((3,3)) #array 3x3 full of ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
a = np.eye(10)
a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [31]:
mn = np.arange(0,50) #evenly spaced values, ints
mn

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [32]:
len(mn)

50

In [50]:
new_mn = mn.reshape(5,10) #reshapes, but doesn't affect the original shape
                          #until it's saved to a new variable


In [48]:
mn

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [49]:
new_mn

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [41]:
o = np.linspace(0,7,10) #evenly spaced values, floats
o

array([0.        , 0.77777778, 1.55555556, 2.33333333, 3.11111111,
       3.88888889, 4.66666667, 5.44444444, 6.22222222, 7.        ])

In [39]:
len(o)

100

In [42]:
o.resize(5,2) #resizes (reshapes) original data
o

array([[0.        , 0.77777778],
       [1.55555556, 2.33333333],
       [3.11111111, 3.88888889],
       [4.66666667, 5.44444444],
       [6.22222222, 7.        ]])

In [51]:
o

array([[0.        , 0.77777778],
       [1.55555556, 2.33333333],
       [3.11111111, 3.88888889],
       [4.66666667, 5.44444444],
       [6.22222222, 7.        ]])

In [55]:
np.random.rand(5,5) #create an array of the given shape with random numbers
                    #[0,1]

array([[0.88665792, 0.6249861 , 0.77884351, 0.83936166, 0.67609859],
       [0.61196264, 0.32003434, 0.83750863, 0.67386055, 0.18162976],
       [0.29959516, 0.53303394, 0.78139843, 0.89866307, 0.34921571],
       [0.53896973, 0.21359994, 0.08843027, 0.46320943, 0.62225682],
       [0.31070772, 0.78233966, 0.64626566, 0.97661607, 0.10794856]])

In [57]:
a = np.random.randn(3,4) #return a sample from the standard normal distribution
a

array([[-0.19774549, -0.08652836,  1.10099427, -0.64334039],
       [-0.45914587,  0.37471909, -1.50123069,  1.40098721],
       [ 0.51750127, -1.19334391, -0.58741625, -0.72261262]])

In [75]:
#generate 10 random ints between 4 and 15 (4 included, 15 excluded)
rn = np.random.randint(4,15,10) #return random ints
rn

array([13, 11, 13, 13, 11, 10, 14,  9,  6,  9])

In [76]:
len(rn)

10

In [81]:
rn.reshape(5,2)

array([[13, 11],
       [13, 13],
       [11, 10],
       [14,  9],
       [ 6,  9]])

In [82]:
tt = np.random.randint(0,10,(4,3)) #generate random ints and shape at the 
                                   #same time
tt

array([[5, 8, 7],
       [2, 8, 6],
       [4, 7, 7],
       [3, 5, 7]])

In [83]:
rn

array([13, 11, 13, 13, 11, 10, 14,  9,  6,  9])

In [84]:
rn[1]

11

In [85]:
rn[-1]

9

In [86]:
rn[3:7]

array([13, 11, 10, 14])

In [87]:
rn[3:]

array([13, 11, 10, 14,  9,  6,  9])

In [88]:
rn[5:-2]

array([10, 14,  9])

In [89]:
rn.resize(2,5)

In [90]:
rn

array([[13, 11, 13, 13, 11],
       [10, 14,  9,  6,  9]])

In [91]:
mm = np.arange(64)

In [92]:
mm

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [93]:
mm.resize(8,8)

In [94]:
mm

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [95]:
mm[2,3]

19

In [96]:
mm[2,]

array([16, 17, 18, 19, 20, 21, 22, 23])

In [98]:
mm[4, 2:5]

array([34, 35, 36])

In [99]:
mm[2:]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [100]:
mm[3:,2:5]

array([[26, 27, 28],
       [34, 35, 36],
       [42, 43, 44],
       [50, 51, 52],
       [58, 59, 60]])

In [101]:
mm[3:,3:]

array([[27, 28, 29, 30, 31],
       [35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47],
       [51, 52, 53, 54, 55],
       [59, 60, 61, 62, 63]])

In [102]:
mm[mm>25]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
       60, 61, 62, 63])

In [103]:
mm > 25

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [104]:
mm[mm >25] = 25 #replacing the values greater than 25 with 25
mm

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25]])

In [105]:
mm1 = mm[3:,3:]
mm1

array([[25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25]])

In [106]:
mm_copy = mm.copy()

In [107]:
mm_copy

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25]])

In [110]:
mm

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25]])

In [111]:
mm == mm_copy

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])