In [2]:
import numpy as np

In [3]:
array1 = np.arange(15, 40)
array1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39])

In [4]:
array2 = np.arange(10, 25)
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

Different integers and different size

In [5]:
even_array1 = np.arange(2, 20, 2)
even_array1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
even_array2 = np.arange(34, 42, 2)
even_array2

array([34, 36, 38, 40])

In [7]:
matrix1 = np.arange(0,36)
matrix1.resize(6,6)
matrix1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [8]:
matrix1[2,1]

13

In [9]:
matrix2 = np.random.randn(5,2)
matrix2

array([[ 0.39922488, -0.87823574],
       [-0.29029323, -0.0546648 ],
       [ 0.32066291, -0.08927648],
       [-0.67779422, -0.09023386],
       [ 1.6692896 , -0.99499717]])

In [10]:
matrix2[-1,-1]

-0.9949971726406037

In [11]:
np.min(matrix2)

-0.9949971726406037

In [12]:
np.max(matrix2)

1.6692895980347227

In [13]:
np.std(matrix2)

0.7297755090750182

In [14]:
np.var(matrix2)

0.532572293645702

In [15]:
np.mean(matrix2)

-0.06863181206620199